### ISSUE TITLE
Where to get the dylib from?

### ISSUE THREAD

**Issue by iluuu1994** [robrix/Auspicion#6]
Hey Rob!

Interesting project!
Where can I get the **libLLVM-3.5.dylib** from? 
Building the entire LLVM project does not produce such a binary.

Thanks!

**Comment by robrix** [comment]
I believe I got mine from [`homebrew`](https://github.com/mxcl/homebrew):

```
$ brew install llvm
```

**Comment by iluuu1994** [comment]
Rad, got it. Thanks!

**Comment by robrix** [comment]
You’re welcome! :smile:
